const prompts = [
// INKTOBER 2016
'fast',
'noisy',
'collect',
'hungry',
'sad',
'hidden',
'lost',
'rock',
'broken',
'jump',
'transport',
'worried',
'scared',
'relax',
'wet',
'battle',
'escape',
'flight',
'squeeze',
'big',
'little',
'one dozen',
'tired',
'box',
'creepy',
'burn',
'surprise',
'wreck',
'friend',
// INKTOBER 2017
'swift',
'divided',
'poison',
'underwater',
'long',
'shy',
'crooked',
'screech',
'gigantic',
'run',
'shattered',
'teeming',
'fierce',
'mysterious',
'fat',
'graceful',
'filthy',
'cloud',
'deep',
'furious',
'trail',
'juicy',
'blind',
'ship',
'squeak',
'climb',
'united',
'found',
// INKTOBER 2018
'poisonous',
'tranquil',
'roasted',
'spell',
'chicken',
'drooling',
'exhausted',
'star',
'precious',
'flowing',
'cruel',
'guarded',
'weak',
'angular',
'swollen',
'scorched',
'breakable',
'drain',
'expensive',
'muddy',
'chop',
'prickly',
'stretch',
'thunder',
'gift',
'double',
'jolt',
'slice',
// INKTOBER 2019
'ring',
'mindless',
'bait',
'freeze',
'build',
'husky',
'enchanted',
'frail',
'swing',
'pattern',
'snow',
'ash',
'legend',
'wild',
'ornament',
'misfit',
'sling',
'tread',
'treasure',
'ancient',
'dizzy',
'tasty',
'dark',
'coat',
'ride',
'injured',
'catch',
'ripe',
// INKTOBER 2020
'fish',
'wisp',
'bulky',
'radio',
'blade',
'rodent',
'fancy',
'teeth',
'throw',
'hope',
'disgusting',
'slippery',
'dune',
'armor',
'outpost',
'trap',
'rip',
'dig',
'buddy',
'hide',
'shoes',
'ominous',
'crawl',
// INKTOBER 2021
'crystal',
'suit',
'vessel',
'knot',
'spirit',
'fan',
'watch',
'pick',
'stuck',
'roof',
'tick',
'collide',
'moon',
'loop',
'fuzzy',
'open',
'leak',
'extinct',
'connect',
'spark',
'crispy',
'patch',
'slither',
'risk',
// INKTOBER 2022
'gargoyle',
'scurry',
'bat',
'scallop',
'bouquet',
'trip',
'match',
'crabby',
'forget',
'kind',
'empty',
'salty',
'scrape',
'ponytail',
'bluff',
'bad dog',
'heist',
'booger',
'tempting',
'ego',
'camping',
'uh-oh',
'gear',
'farm',
// INKTOBER 2023
'dream',
'spiders',
'path',
'dodge',
'golden',
'drip',
'toad',
'bounce',
'fortune',
'wander',
'spicey',
'rise',
'castle',
'dagger',
'angel',
'saddle',
'plump',
'chains',
'scratchy',
'celestial',
'shallow',
'dangerous',
'remove',
'beast',
'sparkle',
'massive',
'rush',
'fire',
// INKTOBER 2024
'backpack',
'discover',
'boots',
'exotic',
'binoculars',
'trek',
'passport',
'hike',
'nomadic',
'snacks',
'remote',
'horizon',
'roam',
'guidebook',
'grungy',
'journal',
'drive',
'ridge',
'uncharted',
'rhinoceros',
'rust',
'expedition',
'scarecrow',
'camera',
'road',
'jumbo',
'navigator',
'violin',
'landmark',
// PEACHTOBER 2018
'pebble',
'key',
'outer space',
'peach',
'camp',
'mountain',
'ice cream',
'music',
'island',
'statue',
'rocket',
'flag',
'planet',
'groceries',
'koala',
'confetti',
'mustard',
'volcano',
'sticks',
'letter',
'tonic',
'forest',
'playground',
'day',
'night',
'birdhouse',
'map',
'bread',
'bones',
// PEACHTOBER 2019
'snail',
'jam',
'waves',
'apple',
'leaves',
'deer',
'soda',
'stars',
'museum',
'boat',
'shelter',
'book',
'peak',
'bird',
'loot',
'clover',
'snack',
'flame',
'herbs',
'drum',
'trophy',
'seat',
'fox',
'light',
'blue',
'sleep',
'berry',
// PEACHTOBER 2020
'home',
'raccoon',
'bridge',
'fish',
'sword',
'wood',
'bugs',
'prize',
'rainbow',
'egg',
'foam',
'horn',
'storm',
'core',
'lilypad',
'warm',
'cool',
'pie',
'shadow',
'rain',
'glow',
'carton',
'hat',
'orchard',
'bloom',
'fossil',
'balloon',
// PEACHTOBER 2021
'tulip',
'smoke',
'hand',
'fall',
'treehouse',
'crown',
'frog',
'gold',
'honey',
'scout',
'toast',
'summit',
'jar',
'uniform',
'sound',
'heart',
'harvest',
'water',
'bottle',
'spade',
'submarine',
'beetle',
'orange',
'cat',
// PEACHTOBER 2022
'cave',
'dandelion',
'cowboy',
'tiger',
'bow',
'trees',
'potion',
'mask',
'boulder',
'lantern',
'field',
'lava',
'tail',
'town',
'smell',
'trunk',
'wing',
'boot',
'spaceship',
'bun',
'globe',
'sprout',
'robot',
'land',
'sea',
'plant',
'whale',
'pet',
'sleepy',
// PEACHTOBER 2023
'bee',
'cosmos',
'sweet',
'grub',
'sprig',
'eye',
'crater',
'citrus',
'pencil',
'nest',
'garden',
'weather',
'sidekick',
'blush',
'snooze',
'candle',
'bulb',
'slingshot',
'tunnel',
'message',
'wand',
'coral',
'ladybug',
'pond',
'chomp',
'float',
'moss',
'spooky',
// PEACHTOBER 2024
'daisy',
'paw',
'sky',
'fawn',
'sketch',
'bud',
'river',
'apricot',
'pixel',
'wheel',
'earth',
'cape',
'burrow',
'lamp',
'owl',
'slow',
'crocodile',
'rest',
'greenhouse',
'village',
'party',
'radish',
'stone',
'grass',
'pony',
'break',
'pearl',
'spider',
// PEACHTOBER 2025
'acorn',
'kite',
'slug',
'gingham',
'poppy',
'strawberry',
'leaf',
'rope',
'critter',
'seagull',
'bark',
'marble',
'brush',
'aquarium',
'hatch',
'whistle',
'melon',
'truck',
'snowflake',
'web',
'paper',
'spots',
'stripes',
'bear',
'axe',
'button',
'sour',
'whisker',
'ghost',
// MAJOR ARCANA
'the fool',
'the magician',
'the high priestess',
'the empress',
'the emperor',
'the hierophant',
'the lovers',
'the chariot',
'strength',
'the hermit',
'wheel of fortune',
'justice',
'the hanged man',
'death',
'temperance',
'the devil',
'the tower',
'the star',
'the moon',
'the sun',
'judgement',
'the world',
// DUMP1
'a baba yagas house',
'a sunbathing cat',
'a red panda owlbear',
'a grumpy black frog',
'a group of squids watching a movie together',
'monkeys playing chess',
'a brightly colored cuttlefish',
'a bathing tiger',
'a confused dog',
'a fish learning to walk',
'a punk rock duck',
'sea monkeys',
'a hermit crab with an unusual home',
'a sleepy owl in a library',
'a fox wearing reading glasses',
'a dancing octopus',
'a hedgehog carrying tiny packages',
'a bear having a tea party',
'a raccoon as a mechanic',
'a fennec fox in the desert',
'a koala detective',
'a snail leaving a rainbow trail',
'a rabbit gardener',
'an otter holding hands with a friend',
'a deer with flowers in its antlers',
'a seal balancing on a beach ball',
'a pelican postman',
'a narwhal knight',
'an axolotl wizard',
'a capybara hot spring bath',
'a crow collecting shiny objects',
'a salamander firefighter',
'a mongoose vs cobra standoff',
'a quokka taking a selfie',
'a tardigrade astronaut',
'an opossum playing dead dramatically',
'a highland cow in a flower field',
'an anglerfish glowing',
'a sea slug garden',
'an alien talking to a teddy bear',
'a creepy cryptid',
'a dragon breathing fire',
'an angel and a devil',
'a bard playing an instrument',
'an annoyed witch',
'a griffin guarding treasure',
'a unicorn in a glade',
'a kelpie by the water',
'a pixie causing mischief',
'a troll under a bridge',
'a goblin marketplace',
'a dwarf master smith',
'a drow spider rider',
'a satyr playing pipes',
'a faun in the woods',
'a zombie rising',
'anxiety as a person',
'a person wearing a straight jacket',
'a person on the moon',
'good vs evil',
'a street performer juggling fire',
'a window washer on a skyscraper',
'an astronaut floating in space',
'a deep sea diver exploring',
'a mountain climber at summit',
'a spelunker in caves',
'a glassblower shaping molten glass',
'a potter at their wheel',
'a blacksmith forging metal',
'a jeweler examining gems',
'a beekeeper among hives',
'a shepherd with their flock',
'a falconer with bird',
'a violinist performing',
'a cellist playing',
'a drummer keeping rhythm',
'a guitarist shredding',
'learning to fly',
'something nostalgic',
'an underwater ruin, come alive',
'exaggerated architecture',
'a floating island chain',
'a cyberpunk alley at night',
'a sky port with airships',
'a koi pond with a bridge',
'a vintage cinema facade',
'a bookshop with cats',
'a street food cart',
'a still life',
'a lemon and an apple are friends',
'a study of color',
'a study of light',
'classical study',
'a polaroid camera',
'an open geode',
'a double rainbow',
'a foggy morning',
'a misty mountain',
'a reflection in water',
'a mushroom circle',
'a steaming cup of coffee',
'a latte art masterpiece',
'a hot chocolate with marshmallows',
'a croissant',
'a pretzel',
'a moon base',
'a generation ship',
'a portal between worlds',
'a mech warrior',
'power armor',
'a skateboarder mid-trick',
'a surfer on wave',
'an olympic athlete',
'a vintage caar',
'a muscle car',
'a double decker bus',
'a hot air balloon',
'a knight in armor',
'a chinchilla dust bathing',
'a platypus detective',
'a toucan with fruit',
'a parrot pirate',
'a snake wearing tiny hat',
'a newt potion master',
'a frog prince before the kiss',
'a toad librarian',
'a lobster chef',
'a crab rave party',
'a shrimp butler',
'a clam keeping secrets',
'a sea lion juggling fish',
'a giraffe window shopping',
'a hippo ballerina',
'a meerkat family portrait',
'a chipmunk with full cheeks',
'a mouse knight',
'a rat scientist',
'a guinea pig in a sweater',
'a fruit bat smoothie stand',
'a vampire bat gentleman',
'a grasshopper fiddler',
'a cicada summer concert',
'a mermaid treasure hunter',
'a grim reaper off duty',
'envy as a person',
'joy as a person',
'sorrow as a person',
'hope as a person',
'courage as a person',
'fear as a person',
'a sword swallower',
'a fortune teller reading cards',
'a tarot card reader',
'a tea leaf reader',
'a tuk tuk taxi',
'an archer drawing bow',
'a sushi chef',
'a pizza toss',
'a ventriloquist dummy',
'a starship shaped like an animal',
'a teddy bear knight defending a bedroom',
'a mushroom wizard casting spores',
'a wizard trapped inside a mirror',
'a giant moth guarding a lantern',
'a celestial fox made of stars',
'a mer-cat lounging on a rock',
'a tiny dragon curled inside a teacup',
'a robot tending a garden',
'a haunted vending machine',
'a crow wizard summoning thunderstorms',
'a cardinal mail carrier in winter',
'a bearded dragon coffee shop owner',
'a turtle postman with a heavy satchel',
'a penguin superhero',
'a bat wearing tiny rain boots',
'a snail riding a skateboard',
'a badger baker making pies',
// DUMP2
'your favorite food',
'a jazz musician',
'combine two animals',
'a person with fruit for hair',
'the gates of a dwarven city',
'a mantis centaur',
'a sleeping stone golem',
'someone trapped in a magic bubble',
'a blacksmith forging a magical axe',
'a dragon with bird feet',
'a dragon with multiple heads',
'a tower of black glass',
'a koi pond',
'the ocean on fire',
'a tree growing around a bike',
'an erupting volcano',
'a haunted house',
'someone wearing a stack of hats',
'a group of friends cooking hot dogs over a bonfire',
'a rodeo clown',
'your favorite monster',
'an aliens symbiotic relationship celebration',
'a cuboid alien',
'an alien bird',
'an alien fish',
'a space pirate',
'an arctic explorer and their companion',
'a bridge between two worlds',
'the vehicle of your dreams',
'twins who are complete opposites',
'two strangers sharing an umbrella',
'a cactus wearing a sweater',
'a mushroom village',
'a mechanical whale',
'a fox with too many tails',
'the worlds worst haircut',
'gravity working sideways',
// DUMP3
'a pig learning to fly',
'a cow jumping over a moon',
'a duck called Adam',
'a cat taking a nap in an unlikely place',
'a silkie chicken getting a haircut',
'a dog exploding',
'animal shaped food',
'a duck in a hat',
'an oddly shaped house',
'a collection of your favorite objects',
'apples and oranges',
'a pierogi shaped bomb so Katy can finally stop posting exploding animals, you can put sauerkraut inside',
'a snow sculpture',
'a fish with legs',
'muscular kirby',
'your favorite beverage as a character',
'a sketch done in 60 seconds or less',
'a self portrait from memory',
'draw a face without looking at your paper/screen',
'add to or edit someones previous prompt submission',
'draw an animal in an unusual colour',
'draw a scene using only vertical lines',
'draw your favourite character',
'draw an old fartist',
'the curliest of fries', 
'the spiciest chili ',
'the coldest ice cream',
'the cheesiest cheese',
'the Hawaiianest pizza',
'fruit pizza',
'a grandma doing a sick trick',
'a dolphin princess',
'a silly dinosaur',
'a kaiju using its signature move',
'instructions on how to pick up a human (if youre a duck)',
'a duck-shaped rabbit',
'a rabbit-shaped duck',
'a ducking duck',
'stacking ducks',
'a space duck in zero gravity',
'add a duck bill to your animal of choice',
'emu soldiers prepping for the Australian emu war',
// DUMP4
'a pocket sized animal',
'a house sized animal',
'an animal in your favorite shoes',
'a horror story in three panels',
'a movie poster',
'a beloved stuffed animal/toy',
'pick the last prompt thats longer than one word and flip its meaning 180º',
'make something in your style to give a shoutout to another regular of this server',
'make something "NSFW" but change what NSFW stands for instead of using its original meaning',
'turn some pet peeve/something that irks you into a JRPG style final boss fight',
'turn any phenomenon/abstract entity into an urban legend and showcase it with a single image story',
'a cathartic emotional beat showcasing a creation of yours',
'attempt someone elses specialty/comfort zone then tag them',
'draw the lamest, worst, lowest hanging fruit joke you can come up with without drawing any fruit',
'paranormal dragon day! any dragon type that looks like one counts (except wyverns, those arent dragons) and give it some legendary lore',
'draw random chaotic scribbles for 120 seconds, then cloudgaze it into something that makes sense',
'a bear riding a tiny bicycle',
'a giraffe trying to limbo',
'a hamster lifting weights',
'a lizard playing guitar',
'an octopus knitting a sweater',
'the wobbliest jello',
'the most dramatic spaghetti',
'a house made entirely of bread',
'a werewolf having a bad hair day',
'a robot learning to dance',
'aliens discovering pizza for the first time',
'a cloud with an attitude problem',
'the sun and moon arm wrestling',
'a very tiny castle',
'combine three random objects into one',
'a mythical creature doing mundane tasks',
'your favorite meme but make it medieval',
'an animal wearing sunglasses indoors',
'a duck teaching a yoga class',
'a raccoon chef preparing suspicious soup',
'a cat giving an important PowerPoint presentation',
'a worm trying on tiny hats',
'a duck cosplaying as another animal',
'a bee attending group therapy',
'a deer learning to skateboard',
'a pigeon running for mayor',
'a bear performing stand-up comedy',
'a koala discovering coffee for the first time',
'a raccoon trying to return something at customer service',
'a totally normal duck (that is clearly not normal)',
// DUMP5
'a goose map',
'sanic',
'draw your favorite pokemon from memory',
'a butt monster',
'fighting 10 geese-sized horses',
'a horse-sized goose',
'goose howard',
'a goose riding a horse',
'a goose dressed as a cowboy',
'a katamari full of geese',
'chickens in the style of Wallace & Gromit',
'bento',
'angry orchestra',
'300 weasels in a trench coat',
'really shitty robots',
'uninstallable Rube Goldberg machine that nobody asked for',
'that one fucking muscle in your upper back',
'wrong constellations',
'knockoff of a popular IP based solely on a drunken description of it',
'one Delicious EGGGGGGGG',
'zombies that suck instead of bite',
'James Baxter, from memory',
'blossom',
'energize',
'fog',
'contrast',
'liquid',
'comfy',
'sparkle',
'crinkle',
// DUMP6
'art goals',
'a mundane 3 panel comic',
'an exciting 3 panel comic',
'an average day',
'the best day ever',
'your town',
'bedroom posters',
'the great divide',
'ghost',
'float like lead',
'tropics',
'boombastic',
'start wearing purple',
'naked in the jungle',
'idk i just work here',
'growing sideways',
'orange juice',
'soak up the sun',
'fake plastic trees',
'bones',
'fairytale',
'i am steve',
'swimming pool',
'a very useless superpower ',
'an Incredibly annoying doorstopper',
'a happy plant',
'a weird handshake',
'a weird animal combination',
'bird-fish',
'tiger-fly',
'horse-monkey',
'elephant-butterfly',
'pizza rat',
'closet of dreams',
'aquarium',
'cyberpunk',
'desert creature',
'ice age village',
'ancient building',
'giant plants',
'dark cave',
'honeycomb',
'i spy',
'wheres waldo',
'street light',
'addiction',
'waves',
'electricity',
'dreamland',
'A matryoshka doll of an object within one meter of you when reading this prompt.',
'an animal plant hybrid',
'a plant growing an unusual food',
'a cake with an unusual ingredient',
'pancakes',
'11am vs 11pm',
'morning',
'afternoon',
'evening',
'dusk',
'twilight',
'golden hour',
'a snack from your childhood',
'typical local food from where you are now',
'an unexpected door knob',
];

module.exports = prompts