
const prompts = [
  'Draw a mystical forest with glowing mushrooms',
  'Create a portrait of a character from your favorite book',
  'Illustrate a cozy coffee shop on a rainy day',
  'Design a futuristic cityscape at sunset',
  'Draw an underwater scene with fantastical creatures',
  'Create a steampunk-inspired invention',
  'Illustrate a peaceful mountain landscape',
  'Draw a magical library with floating books',
  'Design a cute animal wearing a tiny hat',
  'Create a space scene with colorful nebulas',
  'Draw a vintage-style travel poster',
  'Illustrate a garden full of impossible flowers',
  'Create a cyberpunk street scene',
  'Draw a cozy cabin in the woods during winter',
  'Design a friendly dragon in a modern setting',
  'Illustrate a bustling marketplace in a fantasy world',
  'Draw a retro-futuristic vehicle',
  'Create a scene from inside a giant tree house',
  'Illustrate a peaceful zen garden',
  'Draw a character based on your favorite song',
  'Create a whimsical tea party scene',
  'Illustrate a lighthouse during a storm',
  'Draw a magical transformation sequence',
  'Design a floating island in the sky',
  'Create a scene from your dream vacation',
  "Illustrate a busy day in an artist's studio",
  'Draw a mysterious door leading to another world',
  'Create a character inspired by your favorite color',
  'Illustrate a peaceful lakeside scene at dawn',
  'Draw a robot learning to paint',
]

module.exports = prompts